Thomas scraper
q349wang/moss pull request #2
Opened 2020-10-16 23:19 UTC by t6george

Aight this should work for the Bulbapedia Pokedex.

This ended up getting mossed because of the many types of Pokemon that exist under one name (for instance, one article talks about Charizard, Mega Charizard X, Mega Charizard Y and Gigantamax Charizard since they are all technically the same Pokemon but they look different).

Because of this I needed to make a state machine that parses the Biology section of each article and associates each paragraph to the appropriate version of the Pokemon that it refers to. It may not work perfectly, but it should work the vast majority of the time. However if an image cannot be matched with a paragraph/sequence of paragraphs, that data point should end up being discarded.

Lmk if you have any questions, code is kinda mossed

2020-10-16 23:23 UTC, q349wang commented
Add new lines to end of files

2020-10-17 01:56 UTC, q349wang commented
It would be good to start a requirements.txt or something for all the pip packages used

2020-10-17 02:04 UTC, q349wang commented on web/scraper/EntityScrapers/PokemonEntityScraper.py
> +            del stateTransitions[ParseStates.Alolan]
Honestly have no clue what this moss is. But I'll trust its just parsing

2020-10-17 02:06 UTC, q349wang commented on web/scraper/EntityScrapers/PokemonEntityScraper.py
> +            for i in range(min(len(imageLinks), len(naturalLanguage)))]
are image urls and natural language guaranteed to be in the same order? What if the lengths are different. Should we use blank natural language if its not found?

2020-10-17 02:07 UTC, t6george commented on web/scraper/EntityScrapers/PokemonEntityScraper.py
> +            del stateTransitions[ParseStates.Alolan]
This handles the case where a Pokemon region such as the Galar Region is mentioned in the biology but the Pokemon does not have a special Galarian form. In other words, if there is no Galarian picture for a pokemon, then ignore the word 'Galarian' if it comes up in the text and treat it as a regular word. Same goes for Alolan Region.

2020-10-17 02:09 UTC, t6george commented on web/scraper/EntityScrapers/PokemonEntityScraper.py
> +            for i in range(min(len(imageLinks), len(naturalLanguage)))]
The images appear in the order of the paragraphs.

By using min(len(imageLinks), len(naturalLanguage)) we make sure that we dont run off the end of one of the lists.

In the odd case that the imageLinks and naturalLanguage lists are not the same length, the remainder of the unmatched data is discarded.

2020-10-17 02:11 UTC, q349wang commented on web/scraper/EntityScrapers/PokemonEntityScraper.py
> +            for i in range(min(len(imageLinks), len(naturalLanguage)))]
Ok got it, so no unlabeled data then?

2020-10-17 02:13 UTC, t6george commented on web/scraper/EntityScrapers/PokemonEntityScraper.py
> +            for i in range(min(len(imageLinks), len(naturalLanguage)))]
No unlabelled data. We drop any text with no associated image and any image with no associated text.

2020-10-17 02:13 UTC, q349wang commented on web/scraper/EntityScrapers/PokemonEntityScraper.py
> +            for i in range(min(len(imageLinks), len(naturalLanguage)))]
Sounds good

2020-10-17 02:14 UTC, q349wang commented
test comment

2020-10-17 02:14 UTC, q349wang commented on web/scraper/ScraperList.py
> +from UrlListBuilders.PokemonUrlListBuilder import *
test comment 2

2020-10-17 02:35 UTC, q349wang requested changes
Add the _pycache_ and .pyc files to a gitignore. Dont think we need them

2020-10-17 02:46 UTC, q349wang approved these changes

2020-10-20 20:03 UTC, merged